apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grade-submission-api
  labels:
    app: grade-submission
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: grade-submission
    release: {{ .Release.Name }}